### ISSUE TITLE
autoSleep(long autoSleep) method is missing in RepeatBuilder class

### ISSUE THREAD

**Issue by puneetkh** [christophd/citrus#124]
Please provide autoSleep(long autoSleep) method in RepeatBuilder class.

**Comment by christophd** [comment]
Why do you need that autoSleep option in normal iterating containers like repeat? The auto sleep has exclusively been added to the on-error container because the sleep will only take place in case some error is raised. Otherwise the auto sleep is not performed in this container.

In a normal iterating container like repeat autoSleep would be executed in all possible scenarios. So you could do the same with just adding a sleep action to the container:

    repeat()
        .until(someCondition)
        .actions(sleep(2000), echo("I am executed in iteration"));
