### ISSUE TITLE
In order to assert an asynchronous request I would like to extract a BLOB from the database

### ISSUE THREAD

**Issue by aaschmid** [christophd/citrus#126]
Hi Christoph,

thanks for this great framework. I would like to extract an asynchronous response from our BAM database (caused by a complex and unchangeable setup which does not run locally ...) . Unfortunately this is not due to the ```toString()``` call in 

https://github.com/christophd/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/actions/ExecuteSQLQueryAction.java#L155

Stopping at this line with a break point will give me the following:

- ```column.getValue()``` => ```[60, 115, 111, 97, 1...```
- ```column.getValue().getClass()``` => ```class [B```
- ```column.getValue().toString()``` => ```[B@34552700```

I know this can be dangerous as the ```byte[]``` can be huge but in my case this is unfortunately the only case (as long as the infrastructure will not change :-( )

If you need any further information, please don't hesitate to ask.

Cheers,
Andreas

**Comment by aaschmid** [comment]
I can even fix that by myself if you tell me how you would like to have it :-)

**Comment by christophd** [comment]
It really makes no sense to store the byte array object hash string as value with its toString() representation. I have added an automatic base64 encoding so that the byte data is storable as string. You can access the data with decode base64 function for further usage.

This could lead to huge amount of data loaded to the memory, but at the moment we can not pass a data handler or input stream object to the test variables and use them later on. So we have to deal with loading the data to the memory for now.

**Comment by aaschmid** [comment]
I have already tested your solution and it is working. Thanks for fixing.
