### ISSUE TITLE
How to extract plaintext payload?

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [christophd/citrus#195]
Is it possible to extract all the payload of a plaintext response (full text)?

**Comment by christophd** [comment]
Since Citrus 2.7 the messages are automatically stored in a local message store. You can access the messages in a test case by its name then.

This feature is described here: http://www.citrusframework.org/reference/html/endpoints.html#local-message-store 

As an alternative you could use a message validation callback that is provided with the message object as described here: http://www.citrusframework.org/reference/html/validation.html#java-dsl-validation-callbacks

The sample in the reference guide uses a marshalling validation callback, but you could also use some base validation callback that works on the plain Citrus message object.

**Comment by Ernesto-Maserati-CH** [comment]
Thank you. I used the workaround because I did not know about the local message store.

Tried now to use the local message store and stumbled about problems.

The Java example in the documentation I cannot really apply since I don't extend from TestNGCitrusTestDesigner but from TestNGCitrusTestRunner as I figured out. I might be good to add "X extends Y" to the examples since the available methods depend on the super class.

Since I never used that super class it was confusing to me to read that after the receive the payload method is used. I only knew that method within a send-context. But here it is used to validate. When using the HttpClientActionBuilder the payload method isn't available for the receive-context because there are "validate" methods. Confusing to me. I would have expected something like "validatePayload" then it would be clear when reading.

I use "com.consol.citrus.dsl.testng.TestNGCitrusTestRunner#http", there is no "name" method after "receive". I could use it later in the chain of commands after messageType(...). But when I wanted to echo it afterwards it said: CitrusRuntimeException: Failed to find stored message of name: 'bla'

I have a workaround and might figure that out somehow. It is more meant for you to see how rough it can be sometimes, for me at least.

**Comment by christophd** [comment]
Examples are not given in all syntax and language variations that is something to definitely improve in future.

The syntax for designer and runner is exactly the same though. In fact they both use the very same builder class behind the scenes. The only difference is that runner methods make use of nested Lambda builders.

Designer:

    http().client(todoClient)
            .receive()
            .response(HttpStatus.OK)
            .name("myResponse")
            .messageType(MessageType.PLAINTEXT)
            .payload("Hello");

Runner:

    http(action -> action.client(todoClient)
            .receive()
            .response(HttpStatus.OK)
            .name("myResponse")
            .messageType(MessageType.PLAINTEXT)
            .payload("Hello")
    );

**Comment by prabha077** [comment]
I am trying to extract the plain text data payload received from MQ and assign it to the variable. Following is the code snippet i am trying. I am getting " FAILURE: Caused by: ClassCastException: com.ibm.jms.JMSMessage cannot be cast to java.lang.String" error. 
private void optSendBackEndRequest(String xmlLocation){
		
			receive(action -> action.endpoint("Backend_AIREQE3").messageType(MessageType.PLAINTEXT)
					.validationCallback(new AbstractValidationCallback<String>() {
						@Override
						public void validate(String payload, Map<String, Object> headers, TestContext context) {
							context.setVariable("REQ_ID", payload);
						}
					}));
			
			echo("${REQ_ID}");

}

Would you please suggest on this?
