### ISSUE TITLE
Enable Citrus to deploy mock server on remote URL at runtime.

### ISSUE THREAD

**Issue by viharnaik** [christophd/citrus#283]
Issue:
Citrus always bring up mock server on the host machine and this can be a bit of pain to configure with Jenkins or any other build tool.

Just an Idea: If we can add remote url on the http server configuration in context file, that would be helpful to have the same server regardless your host. 

Workaround:
1. For local testing we have been updating all the services from Dev environment to host ip address. 
2. For Jenkins test run, we have been updating all the service from Dev environment to Jenkins ip address

**Comment by toschneck** [comment]
Just one suggestion to solve your problem. You can use the citrus docker-image, this will create the server inside of a container and you wan't get any port/ip conflicts, see: https://github.com/christophd/citrus-docker-images

**Comment by christophd** [comment]
I do not see how we can change the host here. Server instances are always started within the Spring application context. This means server host will always be the same machine unless using Docker for the whole Citrus test execution as suggested by toschneck. 

What exactly is the problem here when executing on Jenkins? In case parallel job execution is the problem you should use dynamic ports in Citrus. You could use Jenkins job execution number as base port for all Citrus http-server instances then.
