### ISSUE TITLE
Dramatically increased build time after reuseForks=false

### ISSUE THREAD

**Issue by svettwer** [christophd/citrus#379]
After updating the TestNG, version we recognized out of memory exceptions in surefire forks. We raised #337 and applied a hotfix where we made `reuseForks` configurable.
This increases the build time dramatically, because the citrus context is recreated in every new fork.
Therefore we should now find the root cause of the memory issue.

BR,
Sven

**Comment by FMAOuroboros** [comment]
![image](https://user-images.githubusercontent.com/25754312/39823306-17074cfa-53ad-11e8-8c7c-c5a30280016f.png)
This is the visualvm history of the org.apache.maven.surefire.booter.ForkedBooter

**Comment by FMAOuroboros** [comment]
Here we've got a picture heap dump: 
![image](https://user-images.githubusercontent.com/25754312/39824421-93f95670-53af-11e8-8a8c-a65a0d1132f5.png)
This clearly shows, that there are a lot of TestNG objects created.

I've no possibility to attach the dump itself, because its round about 3GB.

**Comment by FMAOuroboros** [comment]
While trying to find the root cause of the issue, I found out that the maven `test` goal is enough to enforce the build to fail.
In this stage, Citrus is not involved but tested with TestNG. So most likely it's a TestNG issue.

*Steps to reproduce*
1. Checkout Citurs
2. Checkout 5912d42b2aa3bf29d19d55c0641e5920e3ac6eae
3. `mvn clean test -f modules/citrus-core/pom.xml`

**Comment by FMAOuroboros** [comment]
Well... While I was preparing an issue for TestNG and tried the steps to reproduce in a plain bash terminal, just to be sure and... the issue was gone!
I'm mostly using the IntelliJ Terminal implementation and was assuming that this wouldn't change anything but it seems that it does.

So in total: The issue only occurs in the IntelliJ Terminal implementation with reusing surefire forks and an TestNG version > 6.11.

Our build server has a similar issue but this may just be caused by something else.

**Comment by FMAOuroboros** [comment]
Closed, because this issue is definitely not caused by citrus in any way

**Comment by FMAOuroboros** [comment]
Even when I thought IntelliJ would have been the problem, the Travis CI build I'm currently implementing has the same issue as our jenkins and as my local workstation in some opaque situations. 
https://api.travis-ci.org/v3/job/377637147/log.txt

I reduced the TestNG version to 6.11 again and this is what visualvm showed me:
![image](https://user-images.githubusercontent.com/25754312/39924602-bebf7d1a-5528-11e8-95f6-b4a6eae7cc49.png)

**Comment by svettwer** [comment]
I further investigated the issue wit 6.14.3.
Here are the scenarios I've tested so far:

Scenario | Issue occurred 
------------ | -------------
git clone + `mvn clean install` in ~/tmp/ | NO |
git clone + `mvn clean install` in ~/IdeaProjects/ | YES |
move repo from ~/tmp/ to ~/IdeaProjects/ | NO |
Travis CI build `dist: trusty`+ `sudo: required` | YES |
Travis CI build `dist: trusty` | YES |
On our  [Jenkins](http://labs-build.consol.de/view/Citrus/job/Citrus_Dev/575/console) with containerized slaves | YES |

So this makes absolutely no sense to me. 
Because the TravisCI setup (#364) had the problem as well, I downgraded TestNG again to 6.11 and with this version, `reuseForks=true` works fine.
Therefore #388 will fix this issue as well.
