### ISSUE TITLE
HTTP Client - Unable to send query param that is enclosed within curly braces

### ISSUE THREAD

**Issue by varunmulloli** [christophd/citrus#51]
I have a use case where my query param contains text within curly braces. For example:

`http://localhost:8080/sample?query={"name":"abcd"}` 
which, when encoded should look like 
`http://localhost:8080/sample?query=%7B%22name%22:%22abcd%22%7D`

To specify the HTTP client for this particular request,

`<citrus-http:client id="sample_client" request-method="GET" request-url="http://localhost:8080/sample?query=&#123;&quot;name&quot;:&quot;abcd&quot;&#125;"/>`

I get **`java.lang.IllegalArgumentException: Not enough variable values available to expand '"name"'`**

When I give it as 

`<citrus-http:client id="sample_client" request-method="GET" request-url="http://localhost:8080/sample?query=%7B%22name%22:%22abcd%22%7D"/>`

all % characters are escaped to %25 while performing the request. So it'll look like

`http://localhost:8080/sample?query=%257B%2522name%2522:%2522abcd%2522%257D`

Please suggest a solution for this. Thanks!

**Comment by christophd** [comment]
The strict answer is that you should never have curly braces in your URL as they are very unsafe for several reasons. I had a look at the IllegalArgumentException that you have reported. This exception comes from Spring trying to interpret the curly braces as URI path variables.

So this is way after Citrus has constructed the URI and passed it to the Http client implementation of Spring' RestTemplate. So I guess you have to find a way to escape the curly braces so that Spring won't interpret them as path variables.

However I would recommend to not use the curly braces in your URL.
